import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <>
      <header>
        <nav>Navbar</nav>
      </header>
      <h1>Todo bien</h1>
      <Link href="/about">About</Link>
      {children}
    </>
  )
}
